name: MacOs Build

on:
  push:
  pull_request:

jobs:
  build-on-macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Cargo Hack Check
        run: cargo hack check --each-feature --lib --tests
      - name: Cargo Hack Test
        run: cargo hack test --each-feature
